### PR TITLE
regitering is working

### LINKED ISSUE #12: A RenderFlex overflowed by 189 pixels on the bottom.
════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 189 pixels on the bottom. 
Exception found in the first screen.

### LINKED ISSUE #19: add registering to app

### PR DESCRIPTION
**Pull request by NIwanska**

### CODE REVIEW

File: smart_aquarium/lib/ui/registerPage.dart [hunk 1]
```diff
@@ -215,38 +265,15 @@ Future<int> registerUser(String username, String email, String password) async {
...
-      }
-      return false;
-    } else {
-      debugPrint('Error when fetching users: ${response.statusCode}');
-      return false;
-    }
-  } catch (e) {
-    debugPrint('Error when fetching users: $e');
-    return false;
+    return '';
```
Comment (mikic202) [inline smart_aquarium/lib/ui/registerPage.dart]: What would happen if insted of returning '' exception was thrown here

File: smart_aquarium/lib/ui/registerPage.dart [hunk 2]
```diff
@@ -102,108 +104,156 @@ class RegisterPage extends StatelessWidget {
...
-                    style: TextStyle(
-                        fontSize: 20.0,
-                        color: Colors.white), // Rozmiar tekstu w przycisku
+                child: Padding(
+                  padding: const EdgeInsets.all(20.0),
+                  child: Column(
+                    mainAxisAlignment: MainAxisAlignment.center,
+                    children: <Widget>[
+                      Image.asset(
+                        'assets/login_logo.png',
```
Comment (mikic202) [inline smart_aquarium/lib/ui/registerPage.dart:134]: This is more of a comment to the other asset, but since we're using pngs anyway wouldn't it be better to use transparent image background instead of white?

File: smart_aquarium/lib/ui/registerPage.dart (hunk 1 above)
Comment (NIwanska) [reply smart_aquarium/lib/ui/registerPage.dart]: I changed it so now when there's exception user will see an error on screen

File: smart_aquarium/lib/ui/registerPage.dart (hunk 2 above)
Comment (NIwanska) [reply smart_aquarium/lib/ui/registerPage.dart:134]: It was a problem with image, I changed it to another with transparent background

**Review by mikic202 — APPROVED** [review]
